import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

/**
 * 
 * @param param0 <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'none'; object-src 'none'; worker-src 'none'; connect-src 'self'; script-src 'self' appssdk.zoom.us"
    />
    <meta http-equiv="Strict-Transport-Security" content="max-age=31536000" />
    <meta http-equiv="X-Content-Type-Options" content="nosniff" />
    <meta name="referrer" content="no-referrer" />
    <meta
      http-equiv="Referrer-Policy"
      content="strict-origin-when-cross-origin"
    />
    <meta http-equiv="Cross-Origin-Resource-Policy" content="cross-origin" />
    <meta http-equiv="Cross-Origin-Embedder-Policy" content="require-corp" />
 * @returns 
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
